name: Android Build CI

on:
  push:
    branches:
      - 'build'

jobs:
  build:
    name: Gerando APK
    runs-on: ubuntu-latest

    steps:
      - name: baixa repo
        uses: actions/checkout@v2

      - name: install node
        run: npm i

      - name: testa
        run: npm run test

      - name: builda o container
        run: docker build -t adotei-back:latest .
